main: me.COAR.CoarMcServer.Main
name: CoarMcServer
version: 1.0
author: COAR_
api-version: 1.16

commands:
   feed: 
   fly: 
   gamemode: 
   god:
   heal:
   ptime:
   pweather: 
   gms: 
      aliases: [gmc, gma, gmsp]